[corp-s3]
type = s3
provider = AWS
access_key_id = AKIAIOSFODNN7EXAMPLE
secret_access_key = wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY
region = us-east-1

[corp-azure]
type = azureblob
account = corpstorage
key = FAKE-AzBlobKey-2024-base64-placeholder/AAAAA==
