"""v0.46 step 2: build a minimal-footprint ShareSift binary via
PyInstaller.

Earlier attempts (v0.38) produced a 1.5GB binary because PyInstaller
auto-collected sklearn's whole tree (200+ submodules), pandas (not
even imported!), and lots of test fixtures. This spec aggressively
trims:

- **Excludes ML training stack entirely** — torch, transformers,
  peft, bitsandbytes, accelerate, datasets, trl, unsloth,
  llama_cpp, kingfisher. These are content-inference and
  content-training only; operators using ``score-paths`` don't
  touch them.
- **Excludes SMB/impacket** — operators using local file lists
  don't need them; SMB-direct operators install via pipx with
  the [smb] extra which adds smbprotocol natively.
- **Excludes pandas, matplotlib, seaborn** — never imported by
  Stage 1 cascade or rule engine, but PyInstaller's hooks pull
  them via sklearn / scipy / lightgbm transitively.
- **Trims sklearn**: includes only ``sklearn.base``,
  ``sklearn.utils``, ``sklearn.tree``, ``sklearn.linear_model``,
  ``sklearn.calibration`` (used by isotonic / beta calibrators)
  + dependencies.
- **Trims numpy/scipy** to runtime-only — no testing fixtures.
- **--onefile** since the binary is intended to drop on a Kali
  box without a separate install dir.

Result target: < 200 MB single binary covering ``score-paths``,
``scan-files`` (rule + extractor — but no content classifier),
``to-snaffler-tsv``, ``query``, ``export``, ``sort``.

Operators wanting SMB-direct, network discovery, or content
classifier use ``pipx install 'sharesift[smb,network-enum,content-inference]'``
instead.

Build:

    uv run python tools/build_pyinstaller.py
    # Output: dist/sharesift (Linux), dist/sharesift.exe (Windows)
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DIST_DIR = REPO_ROOT / "dist-binary"
SPEC_PATH = REPO_ROOT / "tools" / "sharesift.spec"


SPEC_TEMPLATE = """# -*- mode: python ; coding: utf-8 -*-
# Generated by tools/build_pyinstaller.py — do not edit by hand.

import os
import sys
from pathlib import Path

REPO_ROOT = Path(SPECPATH).resolve().parent

block_cipher = None

# Hidden imports — modules PyInstaller's static analysis misses
# because they're imported lazily inside functions.
hidden_imports = [
    # Legacy compat shim — joblib-pickled models reference truffler.*
    'truffler',
    'truffler.features',
    'truffler.path',
    'sharesift.cli',
    'sharesift.path',
    'sharesift.content_rules',
    'sharesift.extract',
    'sharesift.tier',
    'sharesift.features',
    'sharesift.ranking',
    'sharesift.engagement',
    'sharesift.engagement.db',
    'sharesift.engagement.export',
    'sharesift.share',
    'sharesift.share.local',
    'sharesift.share.exclusions',
    'sharesift.output',
    'sharesift.output.snaffler_tsv',
    'sharesift.rules',
    'sharesift.rules.extra_rules',
    'sharesift._output',
    # Runtime deps the import-graph misses
    'lightgbm',
    'lightgbm.sklearn',
    'sklearn.tree._classes',
    'sklearn.utils._bunch',
    'sklearn.calibration',
    'betacal',
    'joblib',
    'numpy._core._methods',
    'numpy._core',
    'scipy.special',
    'scipy.sparse',
    'tqdm',
    'pydantic',
    'pydantic_core',
]

# Aggressive exclusions: ML training stack, optional extras,
# pandas/matplotlib/seaborn (never imported but pulled by hooks).
excludes = [
    # Content-inference + training stack — content classifier is
    # not in the Stage-1 binary
    'torch',
    'transformers',
    'peft',
    'accelerate',
    'bitsandbytes',
    'datasets',
    'trl',
    'unsloth',
    'llama_cpp',
    'llama_cpp_python',
    'kingfisher',
    'datasketch',
    # Plotting / pandas — never imported by Stage 1
    'pandas',
    'matplotlib',
    'seaborn',
    'IPython',
    'jupyter',
    'notebook',
    # SMB / network — operators use pipx[smb] for these
    'smbprotocol',
    'spnego',
    'impacket',
    # PDF / OOXML — content stage, opt-in
    'pypdf',
    # Live verification — opt-in
    'requests',
    'paramiko',
    'ldap3',
    'jwt',
    'boto3',
    'botocore',
    # Report rendering — opt-in
    'jinja2',
    # Pysnaffler integration — opt-in
    'pysnaffler',
    # Streamlit (labeling UI) — opt-in
    'streamlit',
    # Test deps
    'pytest',
    'mypy',
    'ruff',
    '_pytest',
]

a = Analysis(
    [str(REPO_ROOT / 'src' / 'sharesift' / '__main__.py')],
    pathex=[str(REPO_ROOT / 'src')],
    binaries=[],
    datas=[
        # Rules JSON files — runtime data the package needs
        (str(REPO_ROOT / 'src' / 'sharesift' / 'rules' / 'snaffler_default.json'),
         'sharesift/rules'),
        (str(REPO_ROOT / 'src' / 'sharesift' / 'rules' / 'extra_rules.json'),
         'sharesift/rules'),
        # Path classifier models (~39 MB combined) — Stage 1 binary
        # needs these to score paths. Bundle relative to model_dir
        # so PathClassifier finds them via sys._MEIPASS in frozen mode.
        (str(REPO_ROOT / 'models' / 'path_classifier_v0_windows'),
         'models/path_classifier_v0_windows'),
        (str(REPO_ROOT / 'models' / 'path_classifier_v0_linux'),
         'models/path_classifier_v0_linux'),
    ],
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# Drop test fixtures across all packages — runtime doesn't need them.
trimmed_datas = []
for src, dest, kind in a.datas:
    if '/tests/' in dest or '/test/' in dest:
        continue
    trimmed_datas.append((src, dest, kind))
a.datas = trimmed_datas

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='sharesift',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,  # strip corrupts scipy's OpenBLAS lib (libscipy_openblas64_)
    upx=False,    # UPX likewise corrupts shared libs
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
"""


def main() -> int:
    if shutil.which("pyinstaller") is None:
        print("ERROR: pyinstaller not installed. Run:", file=sys.stderr)
        print("  uv run pip install pyinstaller", file=sys.stderr)
        return 1

    # Write the spec
    SPEC_PATH.parent.mkdir(exist_ok=True)
    SPEC_PATH.write_text(SPEC_TEMPLATE, encoding="utf-8")
    print(f"Wrote spec → {SPEC_PATH}")

    # Clean previous build
    if DIST_DIR.exists():
        shutil.rmtree(DIST_DIR)
    work_dir = REPO_ROOT / "build-pyinstaller"
    if work_dir.exists():
        shutil.rmtree(work_dir)

    # Run PyInstaller
    cmd = [
        "pyinstaller",
        "--clean",
        "--noconfirm",
        "--distpath", str(DIST_DIR),
        "--workpath", str(work_dir),
        str(SPEC_PATH),
    ]
    print(f"Running: {' '.join(cmd)}")
    proc = subprocess.run(cmd, cwd=REPO_ROOT)
    if proc.returncode != 0:
        print(f"PyInstaller failed (exit {proc.returncode})", file=sys.stderr)
        return proc.returncode

    # Report binary size
    binary = DIST_DIR / "sharesift"
    if binary.exists():
        size_mb = binary.stat().st_size / (1024 * 1024)
        print(f"\nBinary built: {binary} ({size_mb:.1f} MB)")
    else:
        print(f"\nERROR: binary not found at {binary}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
